name: Create and Push Docker Image's to GCR

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        default: ${{ github.event.repository.name }}
      tag:
        type: string
      
    secrets:
     gcp_project_id:
       required: true
     service_account_key:
       required: true
     token:
       required: true
       
jobs:
  gcr_docker_deployer:
    runs-on: ubuntu-latest
    
    env:
      full_repo_name: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{inputs.image_name}}
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.service_account_key }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
#     - name: GCR Auth
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         gcp_project_id: ${{ secrets.gcp_project_id }}
#         service_account_email: ${{ secrets.service_account_email }}
#         service_account_key: ${{ secrets.service_account_key }}
#       if: success() 
    
    - name: Authenticate Docker
      run: gcloud auth configure-docker --quiet
    
    - name: Clone Repositry
      uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: docker build -t $full_repo_name .
      if: success()
      
    # Twistlock CI Scan?
    # if: success()
    
    - name: Push Docker image
      run: docker push $full_repo_name
