name: Create and Push Docker Image's to GCR

on:
  workflow_call: 
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
      
    secrets:
     gcp_project_id:
       required: true
     service_account_email:
       required: true 
     service_account_key:
       required: true
     token:
       required: true
       
jobs:
  gcr_docker_deployer:
    runs-on: ubuntu-latest
    
    steps:
    - name: GCR Auth
      uses: google-github-actions/setup-gcloud@master
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Authenticate Docker
      run: gcloud auth configure-docker --quiet
    
    - name: Clone Repositry
      uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: docker build -t ${{inputs.image_name}} .
      
    # Twistlock CI Scan?
    
    - name: Push Docker image
      run: docker push ${{inputs.image_name}}
