name: Terraform Build Action

on:
  workflow_call:
    inputs:
      terraform_base_name:
        type: string
      gcp_region:
        type: string
        default: "us-central1"
      TF_VAR_gcr_repo_name:
        type: string
        default: ${{ github.event.repository.name }}
      
    secrets:
     gcp_project_id:
       required: true
     service_account_key:
       required: true
     token:
       required: true
       
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Clone Repositry
      uses: actions/checkout@v2
      
    - name: Set TF_VAR variables
      run: |
        export TF_VAR_gcr_repo_name=${{inputs.TF_VAR_gcr_repo_name}}
        echo $TF_VAR_gcr_repo_name
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.service_account_key }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      if: success()
      
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: false

      
  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_validate
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Clone Repositry
      uses: actions/checkout@v2
    
    - name: Set TF_VAR variables
      run: |
        export TF_VAR_gcr_repo_name=${{inputs.TF_VAR_gcr_repo_name}}
        echo $TF_VAR_gcr_repo_name
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.service_account_key }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      if: success() 
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false
      env:
        gcr_repo_name: ${{inputs.TF_VAR_gcr_repo_name}}
      
  terraform_apply:
    runs-on: ubuntu-latest
    needs: [terraform_validate, terraform_plan]

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Clone Repositry
      uses: actions/checkout@v2
    
    - name: Set TF_VAR variables
      run: |
        export TF_VAR_gcr_repo_name=${{inputs.TF_VAR_gcr_repo_name}}
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.service_account_key }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      if: success() 
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: false
