name: Terraform Build Action - AWS

on:
  workflow_call:
    inputs:
      TF_VAR_repo_name:
        type: string
        default: ${{ github.event.repository.name }}
      
    secrets:
     AWS_ACCESS_ID:
       required: true
     AWS_ACCESS_SECRET:
       required: true
       
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Clone Repositry
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: us-east-1
        role-duration-seconds: 1200
        role-session-name: GitHub Actions Session
      if: success()
      
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: false

      
  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_validate
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Clone Repositry
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: us-east-1
        role-duration-seconds: 1200
        role-session-name: GitHub Actions Session
      if: success()
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false
      env:
        TF_VAR_repo_name: ${{inputs.TF_VAR_repo_name}}
      
  terraform_apply:
    runs-on: ubuntu-latest
    needs: [terraform_validate, terraform_plan]

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Clone Repositry
      uses: actions/checkout@v2
    
    - name: Set TF_VAR variables
      run: |
        export TF_VAR_repo_name=${{inputs.TF_VAR_repo_name}}
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: us-east-1
        role-duration-seconds: 1200
        role-session-name: GitHub Actions Session
      if: success()
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: false
      env:
        TF_VAR_repo_name: ${{inputs.TF_VAR_repo_name}}
